{{- if and .Values.rbac.create (eq .Values.rbac.scope "Role") }}
{{- $namespaces := default (list .Release.Namespace) .Values.rbac.namespaces }}
{{- range $ns := $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubeagent.fullname" $ }}
  namespace: {{ $ns }}
  labels:
    {{- include "kubeagent.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubeagent.fullname" $ }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubeagent.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
