apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeagent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeagent.labels" . | nindent 4 }}
type: Opaque
data:
  agent-token: {{ .Values.platform.token | default "" | b64enc | quote }}
  platform-url: {{ .Values.platform.url | b64enc | quote }}
