{{- if and (not .Values.existingSecret) (or .Values.platform.token .Values.platform.url) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.platform.token }}
  agent-token: {{ .Values.platform.token | b64enc | quote }}
  {{- end }}
  {{- if .Values.platform.url }}
  platform-url: {{ .Values.platform.url | b64enc | quote }}
  {{- end }}
{{- end }}
