{{- if and (not .Values.existingSecret) .Values.platform.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-agent.labels" . | nindent 4 }}
type: Opaque
data:
  agent-token: {{ .Values.platform.token | b64enc | quote }}
{{- end }}
